### ISSUE TITLE
Missing html5lib dependency

### ISSUE THREAD

**Issue by mgax** [torchbox/wagtail-news-template#11]
After building a new Wagtail site with this template, the homepage crashes because there's no `html5lib` installed:

<img width="1276" alt="Screenshot 2024-06-22 at 12 13 25" src="https://github.com/torchbox/wagtail-news-template/assets/27617/7eea3096-6575-4ebc-b813-b58ff69bd59a">

**Comment by zerolab** [comment]
Can you provide the full traceback, please?
Wagtail 6.1 dropped the html5lib deps ([ref](https://docs.wagtail.org/en/stable/releases/6.1.html#maintenance))

**Comment by mgax** [comment]
> Can you provide the full traceback, please?

https://gist.github.com/mgax/0003f747b5eb7418bd78381976083be2

I'm pretty sure the issue is caused by the sequence in the readme:
- step 2: run `pip install wagtail` (installs most recent version of wagtail).
- step 3: run `wagtail start ...` (creates `requirements.txt` but then it's never used).
- step 6: run `make start` (in the same virtualenv).

Jake's PR adds an extra step in the Readme which fixes this issue: https://github.com/torchbox/wagtail-news-template/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R47.

**Comment by zerolab** [comment]
ah, this comes from https://github.com/torchbox/wagtail-news-template/blob/main/project_name/utils/models.py#L351 which explicitly asks for `html5lib`
