### ISSUE TITLE
Error validation on form page

### ISSUE THREAD

**Issue by songproducer** [torchbox/wagtail-news-template#15]
Currently all fields show {{ error {{

Your message here

{{ error {{

Message
Write your email here so we can reply to you!

{{ error {{

**Comment by zerolab** [comment]
ref: https://github.com/torchbox/wagtail-news-template/blob/7ebe6827be60b1fd6007cd9a265e601c2e6b16b2/templates/components/form-field.html#L15

**Comment by zerolab** [comment]
Will be fixed by #17
